#!/bin/sh

# Copyright (C) 2018 Bibliotheca Alexandrina <www.bibalex.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

f="$(readlink -f "$PWD")"

if [ "$f" = / ]; then
  f=
fi

r="$(echo "$f" | tr / \\n | tail -n +2 | while read i; do
  a="$a/$i"
  echo "$a/.pairsync.remote"
done | tac | while read i; do
  if [ -e "$i" ]; then
    cat "$i"
    break
  fi
done)"

if [ -z "$z" ]; then
  echo "Remote not found" >&2
  exit 1
fi

if ! opts=`getopt -q -o "" -l "pull,push" -- "$@"`; then
  echo "Bad invocation" >&2
  exit 1
fi

eval set -- "$opts"

while true; do
  case "$1" in
    --pull)
      pull=1
      ;;
    --push)
      push=1
      ;;
    --help)
      usage
      exit 0
      ;;
    --)
      shift
      break
      ;;
  esac
  shift
done

if [ "$pull" = 1 ] && [ "$push" = 1 ]; then
  echo "Pull/push selected together" >&2
  exit 1
fi

if [ -e "$f/.pairsync.includes" ]; then
  incl="--include-from=$f/.pairsync.includes"
  excl="--exclude=/*"
fi

# - Wildcard in source path avoids assuming top dir is writable.
# - Wildcard is processed by shell in push from local.
# - Wildcard is processed by rsync in pull from remote.
# - Push to /afs is very slow with -g (implied by -a) fo some reason.

if [ "$push" = 1 ]; then
  rsync -a --no-g --no-o --delete "$incl" "$excl" "$f"/* "$r"/
else
  rsync -a --no-g --no-o --delete "$incl" "$excl" "$r/*" "$f"/
fi
